### PR TITLE
Read from boot.properties

### PR DESCRIPTION
**Pull request by martinklepsch**
Most of the work here has been done by @pesterhazy. Thanks :)

via boot-clj/boot#433, #12 & #5

- [x] Make sure https://github.com/boot-clj/boot/wiki/Configuring-Boot is up to date
- [x] document changes in Changelog

### CODE REVIEW

**Review by arichiardi — APPROVED** [review]
LGTM

**Comment by arichiardi** [comment]
Might be worth changing also this section: https://github.com/boot-clj/boot/wiki/Configuring-Boot#note-about-boot_jvm_options

**Comment by martinklepsch** [comment]
Thanks for finding this @arichiardi, updated: https://github.com/boot-clj/boot/wiki/Configuring-Boot#note-about-boot_jvm_options--boot_java_command

**Comment by alandipert** [comment]
Had to revert this because the bash had typos. Here's a diff of the script I made that seems closer to working:

```
diff --git a/Users/alandipert/github/boot-clj/boot-bin/src/head.sh b/tmp/boot.sh
old mode 100644
new mode 100755
index d5a9aba..bb8d2dd
--- a/Users/alandipert/github/boot-clj/boot-bin/src/head.sh
+++ b/tmp/boot.sh
@@ -36,10 +36,10 @@ if [[ -n "${BOOT_JVM_OPTIONS-}" ]]; then
 fi
 
 # Setting env vars for java process so this information can be retrieved easily
-export BOOT_JAVA_COMAND="$java_command"
-export BOOT_JVM_OPTIONS="$options"
+export BOOT_JAVA_COMMAND="$java_command"
+export BOOT_JVM_OPTIONS="${options[@]}"
 
 self="${BASH_SOURCE[0]}"
 selfdir="$(cd "$(dirname "${self}")" ; pwd)"
 selfpath="$selfdir/$(basename "$self")"
-exec "$java_command" "${options[@]-}" -Dboot.app.path="$selfpath" -jar "$0" "$@"
+exec "$java_command" "${options[@]}" -Dboot.app.path="$selfpath" -jar "$0" "$@"
```

Please make fixes and test.

**Pull request merged**
